[package]
name = "starknet_token"
version = "0.1.0"
edition = "2023_10"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.8.0" }
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.13.1" }
starknet = "2.4.1"

[[target.starknet-contract]]
casm = true

[[tool.snforge.fork]]
name = "SN_TESTNET"
url = "https://starknet-testnet.public.blastapi.io/rpc/v0_6"
block_id.number = "923700"

[[tool.snforge.fork]]
name = "SN_SEPOLIA"
url = "https://starknet-sepolia.public.blastapi.io/rpc/v0_6"
block_id.number = "11900"
