[sncast.default]
account = "testnet"
accounts-file = "~/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "https://starknet-testnet.public.blastapi.io/rpc/v0_6"

[sncast.mainnet]
account = "mainnet"
accounts-file = "~/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "https://starknet-mainnet.public.blastapi.io/rpc/v0_6"
